### ISSUE TITLE
purge.py

### ISSUE THREAD

**Issue by LordFaggot** [sollicitudin/FacebookGroupScripts#1]
purge.py is not working saying requests is not defined

**Comment by sollicitudin** [comment]
in command line type `pip install -r requirements.txt`

**Comment by LordFaggot** [comment]
i did

**Comment by LordFaggot** [comment]
in first script you need to move the imports above where you copy pasta cookie, access token, gid, and uid

**Comment by sollicitudin** [comment]
have you tried it? is it working for you?

**Comment by LordFaggot** [comment]
# paste your info here, inside the '' mark
cookie = 'paste your cookie here. for how to get it, please view README.md section Cookie'
access_token = 'your access token. for how to get it, please view README.md'
my_id = 'paste your user ID here. for how to get it, please view README.md section Facebook ID'
group_id = 'your group ID. for how to get it, please view README.md section Group ID'
# end section
       
        import requests
        import re

access_token = 'EAAAAUaZA8jlABAKLZBkvR2pjtfZCD8xEICb8ZCB2sS8ZBJvRZBaAx1AojKuXsc2N2cKJXoOf0tqVY2rZAUyMwgFX4ZBmrHMDS0UOg5tXHEwugOrgkeExZBThS6ZBvv7ad1XJtjzq9rqDCSxuqCTvJGkhlkACgVupP9WI6hsl70wvjCr3jBrNmCqxkn'
cookie = 'datr=ByatWR_IoGlZnplYNAMIxKbq; sb=ByatWb2skTQ4g_latWyFPgrO; dpr=1.25; c_user=100002662774219; xs=23%3ArhLMW3uLz8DXcQ%3A2%3A1525488690%3A13618%3A6154; pl=n; fr=0uYhrHrdavvnJ3JYq.AWWXkOB5JfJJlTnRfZ6cxHg8_AI.BZrSYH.rZ.AAA.0.0.Ba7Th-.AWXSHgBz; wd=1535x474; presence=EDvF3EtimeF1525497767EuserFA21B02662774219A2EstateFDsb2F1525497567373EatF1525497766042Et3F_5bDiFA2user_3a1B00415828805A2EoF12EfF19C_5dEutc3F1525497631862G525497767976CEchFDp_5f1B02662774219F906CC; act=1525497774392%2F243'
group_id = '274304963025835'
my_id = '100002662774219'#'100002662774219'

class User(object):
    def __init__(self):
        self.cookie = cookie
        self.access_token = access_token
        self.id = my_id
        self.group_id = group_id


        headers = { 'content-type' : 'application/x-www-form-urlencoded',
                    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36',
                    'cookie' : self.cookie }
        r = requests.get('https://m.facebook.com/ajax/dtsg/?__ajax__=true', headers=headers)
        self.fb_dtsg = re.search('[^"]+:[^"]+', r.text).group(0)

    def getCookie(self):
        return self.cookie

    def getAccessToken(self):
        return self.access_token

    def getID(self):
        return self.id

    def getGroupID(self):
        return self.group_id

    def getDTSG(self):
        return self.fb_dtsg

class Group(object):
    def __init__(self):
        self.id = group_id
        self.admin = User()

    def remove(self, uid):
        remove_url = 'https://www.facebook.com/ajax/groups/members/remove.php'    
        headers = { 'content-type' : 'application/x-www-form-urlencoded',
                    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36',
                    'cookie' : self.admin.getCookie() }
        params = {'group_id': self.admin.getGroupID(),
            'user_id': uid, 
            'is_undo': '0',
            'source': 'profile_browser',
            'dpr': '1.5'}
        remove_payload = {'fb_dtsg': self.admin.getDTSG(),
                      'confirm': 'true',
                      '__user': self.admin.getID(),
                      '__a': '1'}
        requests.post(remove_url, headers=headers, data=remove_payload, params=params)

    def getID(self):
        return self.id

    def getAdmin(self):
        return self.admin

**Comment by LordFaggot** [comment]
![image](https://user-images.githubusercontent.com/23299160/40054915-f2f7bbf2-580b-11e8-8021-ece643fa453b.png)

**Comment by LordFaggot** [comment]
i'd say so bud, good job on this. and the speed is remarkable, its fucking instant.
